### ISSUE TITLE
Remove selected line underline

### ISSUE THREAD

**Issue by rauchg** [yosiat/oceanic-next-vim#1]
By default

![](https://cloudup.com/cdX6gQysXRt+)

I think it's too distracting. I got rid of it with:

```
hi CursorLine guifg=NONE guibg=#2d3c45 ctermbg=237 gui=NONE term=NONE cterm=NONE
```

**Comment by yosiat** [comment]
Hi @rauchg ,
I removed the cursor line - 
https://github.com/yosiat/oceanic-next-vim/commit/a02222380773693fc241ee83b96106c8fcb474ae

Thanks for the feedback :+1:

**Comment by jgsn13** [comment]
Hello @rauchg thanks man!
